# Generated by Django 5.0.6 on 2024-05-13 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='enddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='board',
            name='payment',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='board',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
