# Generated by Django 5.0.6 on 2024-05-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_enddate_board_payment_board_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='roadAddress',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='board',
            name='roadAddressDetail',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='board',
            name='zonecode',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
