# Generated by Django 3.2.25 on 2024-05-20 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=20)),
                ('writetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=500)),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'post_data',
            },
        ),
        migrations.CreateModel(
            name='storeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(max_length=50)),
                ('storeowner', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=20)),
                ('telnumber', models.CharField(max_length=12)),
                ('zonecode', models.CharField(default=0, max_length=30, null=True)),
                ('roadAddress', models.CharField(default=0, max_length=30, null=True)),
                ('roadAddressDetail', models.CharField(default=0, max_length=30, null=True)),
            ],
            options={
                'db_table': 'store_data',
            },
        ),
    ]
