# Generated by Django 3.2.25 on 2024-05-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petgrooming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='closetime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storedata',
            name='opentime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storedata',
            name='profileImg',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m'),
        ),
    ]
