# Generated by Django 3.2.25 on 2024-05-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petgrooming', '0002_auto_20240520_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='writer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
