# Generated by Django 3.2.25 on 2024-05-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petgrooming', '0004_auto_20240529_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='storedata',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='storedata',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='store_data', to='petgrooming.Qualification'),
        ),
    ]
