# Generated by Django 3.2.25 on 2024-05-29 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petgrooming', '0005_auto_20240529_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='storedata',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='qualification',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='qualification',
            name='pet_shop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='petgrooming.storedata'),
        ),
        migrations.AddField(
            model_name='storedata',
            name='readcount',
            field=models.IntegerField(default=0),
        ),
    ]
