# Generated by Django 3.2.25 on 2024-05-31 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petgrooming', '0006_auto_20240529_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='pet_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='petgrooming.storedata'),
        ),
        migrations.CreateModel(
            name='CommentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('writetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='petgrooming.storedata')),
            ],
            options={
                'db_table': 'comment_data',
            },
        ),
    ]
