# Generated by Django 3.2.25 on 2024-06-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petgrooming', '0007_auto_20240531_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LikeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeuser', models.CharField(blank=True, max_length=100)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedata', to='petgrooming.storedata')),
            ],
            options={
                'db_table': 'store_like',
            },
        ),
    ]
