# Generated by Django 3.2.25 on 2024-06-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petgrooming', '0008_auto_20240601_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images'),
        ),
    ]
