# Generated by Django 3.2.25 on 2024-06-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petgrooming', '0009_alter_storedata_store_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedata',
            name='location',
        ),
        migrations.AddField(
            model_name='storedata',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storedata',
            name='detail_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storedata',
            name='extra_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storedata',
            name='postcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
