# Generated by Django 3.2.25 on 2024-06-03 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petgrooming', '0010_auto_20240603_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_user', models.CharField(blank=True, max_length=100)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='petgrooming.storedata')),
            ],
            options={
                'db_table': 'store_scrap',
            },
        ),
    ]
