# Generated by Django 5.0.6 on 2024-05-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_roadaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
