# Generated by Django 5.0.6 on 2024-05-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_board_imgfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='type',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
