# Generated by Django 3.2.25 on 2024-05-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, verbose_name='ID')),
                ('password', models.CharField(max_length=20, verbose_name='PW')),
                ('usernickname', models.CharField(max_length=20, verbose_name='NICKNAME')),
                ('phonenumber', models.IntegerField(max_length=20, verbose_name='TEL')),
                ('email', models.EmailField(max_length=100, verbose_name='EMAIL')),
            ],
            options={
                'db_table': 'userData',
            },
        ),
    ]
