# Generated by Django 3.2.25 on 2024-05-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phonenumber',
            field=models.IntegerField(verbose_name='TEL'),
        ),
    ]
