# Generated by Django 3.2.25 on 2024-05-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userdata_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phonenumber',
            field=models.CharField(max_length=11, verbose_name='TEL'),
        ),
    ]
